### ISSUE TITLE
Improve logging auto-configuration

### ISSUE THREAD

**Issue by aaugustin** [rq/django-rq#191]
django-rq attempts to autoconfigure the `'rq.worker'` logger here:
https://github.com/ui/django-rq/blob/43b6eb344ceb7d0be9677aae544850855237eba2/django_rq/management/commands/rqworker.py#L18-L26

This pattern was copied from `rq` itself, however, the check for an existing logging configuration is incorrect and initializes the logger even if its messages would be caught by an explicitly, properly configured root logger.

https://github.com/nvie/rq/commit/fe122ac7993b972ff2230fe4987a0a23b4c43e79 made changes and slightly improved the situation, but it's still incorrect, as described in https://github.com/nvie/rq/issues/750.

This ticket applies to django-rq exactly like it does to rq. Relevant parts:

I would like to suggest the following pattern:

``` python
try:
    logger.hasHandlers
except AttributeError:
    # Compatibility shim for Python < 3.2
    has_handlers = bool(logger.handlers)
else:
    has_handlers = logger.hasHandlers()

if not has_handlers:
    # automagically configure logging
```

You could also use something more complicated than `bool(looger.handlers)` for Python 2 (but I don't care about that part, it would make sense to favor stability above correctness on Python 2 at that point).

**Comment by aaugustin** [comment]
Actually I'm wondering if you could rely on rq to do that setup? It's unclear to me why you need to duplicate that logic.

**Comment by selwin** [comment]
I'm not a logging expert by any means (and I don't have the time to look into it) so I'd welcome any suggestions and PR to make these libraries behave more correctly. If you could issue a PR to RQ repo, it would also be great.

**Comment by aaugustin** [comment]
I'm not a logging expert either... As far as I know, it's an antipattern for libraries to configure logging; that should be done by the application that embeds them. I could send a PR that removes logging setup code and only keeps logging calls, but that doesn't seem constructive; I assume that code exists for a reason.

**Comment by selwin** [comment]
Removing logging setup code is not something we want to do I think.

What we wanted to do is make RQ as easy to use as possible so that means useful logging by default (i.e when you run `rqworker` it should give you informational messages).

To achieve that, we check whether `rq.worker` logger is configured when the worker is run. If logger for RQ is not configured, we configure a default logging configuration for RQ. That's the idea anyway, if there's anything we can do to improve the way we check for existing handlers, we're open to suggestions :).
