### ISSUE TITLE
"async" function argument causing SyntaxError since Python3.7

### ISSUE THREAD

**Issue by Madi7** [rq/django-rq#295]
In django_rq/queues.py:

    def get_queue(name='default', default_timeout=None, async=None,
                  autocommit=None, queue_class=None, job_class=None, **kwargs):
        ...

Python3.7's release note:

    Backwards incompatible syntax changes:

        async and await are now reserved keywords.

**Comment by Flimm** [comment]
Note that the library `rq` has a similar issue: https://github.com/rq/rq/issues/921

They decided to switch from using the `async` argument to using the `sync` argument. So instead of using `async=True`, you would use `sync=False`. The fix hasn't been released on PyPI yet, the current version of `rq` (0.11) still isn't Python 3.7 compatible.

**Comment by alexrussell** [comment]
Looks like it's now fixed by renaming `async` to `is_async`, rather than inverting it to `sync`. See https://github.com/rq/rq/pull/977 / https://github.com/rq/rq/commit/c2b939d2df7df2bd0a6e5a73823a07baecc17895.

They haven't cut a new release yet, but it'd make sense to do the same and just not cut yet.

**Comment by dbinetti** [comment]
They have released `0.12.0` on PyPi.  https://github.com/rq/rq/commit/6a376191d92bc663be71390db7405820761a0ecb

**Comment by selwin** [comment]
Yes, `async` has been renamed to `is_async` in RQ 0.12. It would be great if someone can open a PR implementing something similar in this repo :)

**Comment by Flimm** [comment]
See my pull request #297
