### ISSUE TITLE
workers crashing:  ValueError: There exists an active worker named ... already

### ISSUE THREAD

**Issue by ccurvey** [rq/django-rq#296]
I've been using django-rq for about four years, and I love it.  I'm trying to port my site to Docker, and use docker-compose in my development environment.  When I start my site with "docker-compose up" (which is supposed to start all my services), my workers crash with a message like:

> ValueError: There exists an active worker named u'00ec99547605.7' already

I suspect that this is because a previous startup registered some workers, but then never cleanly shut them down.   (For Docker fans, I'm actually running my Redis as a separate service outside of Docker.)

Is there a way to tell Django-RQ that these workers no longer exist?  Or a way to configure them so that they time out quickly (at least in development?)

**Comment by selwin** [comment]
Workers should automatically timeout after a brief period of inactivity. 

Do you know what's causing docker images to keep spawning workers with the same name?

**Comment by ccurvey** [comment]
how long is "brief"?   Here's my sequence:

1. Start system with `docker-compose up` (starts a bunch of workers).
2. Test what I'm working on.  Notice issue.  Change code that is driven by worker.
3.  Ctrl-C to stop docker containers.  (I try let docker-compose shut down gracefully, and not double-ctrl-c to kill it immediately.
4.  Restart docker compose (`docker compose up`).  Then I get the errors.

Is there a way for me to influence how long that timeout is?   Either via configuration, or a custom worker, or something else?

**Comment by mrgordon** [comment]
This is a problem with RQ itself and it happens to me on occasion. I agree with @ccurvey that it isn't time-based. It seems to leave state in Redis that corrupt the ability to restart the worker after shutdown

**Comment by selwin** [comment]
@ccurvey the default TTL is 420 seconds.

To elaborate more on how this works, when an RQ worker is created, it generates a "random" name in `hostname.pid` format. This is clearly not friendly towards systems that are rebooted often like @ccurvey 's use case.

Since the use of Docker will only become more common and RQ already generates a "random" name for the worker anyway, let's change the default key format to `hostname.pid.uuid_string`.

Can someone please open a PR for this?

**Comment by remort** [comment]
Quick fix to avoid this crash.
`./manage.py rqworker --name $(date +%s)`

**Comment by selwin** [comment]
RQ >= 1.0 already uses uuid as part of it's worker name so this should no longer be an issue.

**Comment by stevennic** [comment]
I'm still seeing this with RQ 1.13.0

**Comment by toti1212** [comment]
I'm still seeing this as well with `rq==1.16.0`

**Comment by selwin** [comment]
@toti1212 did you set the worker name manually? Or it could also be there's a process that duplicates the worker.

**Comment by mik3y** [comment]
We recently reproduced this issue. Perniciously, it caused our worker to die semi-permanently, as the exception in question essentially prevents the worker from launching when state is corrupted.

I believe it requires the following two conditions:
1. The worker uses a non-random name. We are using custom worker names like `worker{1,2,3}.production`.
2. A previous instance of that worker crashed.

Looking at the code, it's straightforward to see how that could happen:
1. On boot, workers call [`register_birth()`](https://github.com/rq/rq/blob/3e2e26e702b21d53a9658e3eadfb966dd3621636/rq/worker.py#L829-L831), which checks for existence of a redis key that is a function of `worker.name`.
2. On normal shutdown, workers call [`register_death()`](https://github.com/rq/rq/blob/3e2e26e702b21d53a9658e3eadfb966dd3621636/rq/worker.py#L856-L865) before exiting in order to clear state and expire that key.
3. On unclean shutdown, nothing seems to perform step 2.

(Nothing about this seems to be _django_ rq specific, by the way.)

Upon discovering this issue, we manually expired the key in redis (e.g. `rq:worker:worker.1:production`) and this allowed the replacement worker to boot.
